open-watcom/open-watcom-v2

bld/clib/posix/c/getline.c
Using `realloc` in `getdelim` is not strictly necessary since we don't care about the previous line/segment's contents when a resizing is needed.  I've been running into some odd realloc() failures on Linux that I haven't tracked down yet.  That said, this commit provides a more reliable and, possibly, efficient way to handle the line allocation.  Additionally, it does correct a minor bug in the code that probably wasn't strictly causing issues.
=> Fixes for getdelim regarding memory allocation

bld/hdr/watcom/pwd.mh
POSIX and Linux has the return values for setpwent/endpwent as void.  The headers needed to be updated.
=> Fixed return value of setpwent/endpwent in headers

bld/f77/wfc/c/option.c, bld/f77/wfc/c/sdcline.c, bld/f77/wfc/h/optinfo.h, bld/f77/wfl/c/wfl.c, bld/wcl/c/owcc.c, bld/wcl/h/clcommon.h
This commit (squash of 5) adds a few new Fortran-centric features, notably:
* Drastically better command-line handling in the Fortran compiler, the "wfl" driver, and the owcc driver by using spawnvp rather than erroneously using spawnlp
* Support for the Fortran compiler in the POSIX wrapper driver (owcc) when a .f or .for file is encountered
* Addition of compiler options to the Fortran compiler for compatibility with other Open Watcom tools (-zq, -fr, -i are now valid)
* Support for combinatorial optimization options in the Fortran compiler (like "-ohxl+" is now processed properly, just like our C compilers)
* Support for spaces in the objects and linked executable name when using wfl or owcc
With support for the Fortran compiler in the POSIX wrapper, we can start to look at providing …
=> Support for Fortran in owcc wrapper.  Improvements to command-line handling in owcc and Fortran compilers.

bld/clib/h/sys386.h, bld/clib/linux/c/timer.c, bld/clib/linux/objects.mif, bld/hdr/watcom/linux/arch/i386/siginfo.mh, bld/hdr/watcom/linux/arch/i386/sigposix.mh, bld/hdr/watcom/linux/arch/mips/siginfo.mh, bld/hdr/watcom/signal.mh, bld/hdr/watcom/sys/types.mh, bld/hdr/watcom/time.mh, docs/doc/lr/libfuns.gml, docs/doc/lr/liblist7.gml, docs/doc/lr/src/tmrcreat.gml, docs/doc/lr/src/tmrdel.gml, docs/doc/lr/src/tmrget.gml, docs/doc/lr/src/tmrover.gml, docs/doc/lr/src/tmrset.gml
Although present in our headers, we didn't have an implementation of the POSIX timers.  This pull request implements (with docs) the following:
* timer_create
* timer_delete
* timer_settime
* timer_gettime
* timer_getoverrun
All functions appear to be working on a Linux kernel that supports timers.
=> Implementation of POSIX timers

bld/wl/c/ideentry.c
There were some strange '#ifdef __OS2__' parts in wl/c/ideentry.c, which caused wlink to crash.
I've disabled them for now (the IDE crashes anyway on startup).
I've successfully compiled 16 and 32 bit OS/2 test programs and 16 bit DOS program on a OS/2 host with this change.
=> Fix crash in wlinkd.dll when running wlink on OS/2

bld/causeway/inc/cwdll.h
Without extern "C" linker couldn't resolve functions in cwdll.lib
=> add extern "C" to make the header work in C++

bld/ui/unix/c/tixparse.c, bld/ui/unix/c/uibios.c, bld/wipfc/configure, bld/wipfc/configure.ac, bld/wipfc/cpp/document.cpp, build.sh, setvars.sh
Some corner problems: 
* if terminfo base can not be found
* if working on linux console with utf8 (not xterm)
* if trying to build WATCOM with gcc 3.4.6 (or with other not c++0x compatible compiler)
* allow to start build WATCOM by running build.sh w/o doing anything else (tuning)
=> Linux issues solving

bld/wgml/test/testlib/makefile, docs/mif/onebook.mif
Some command.com's do not understand the unix's LF lines.
=> convert wgml.bat to CR-LF line-ending

build.sh
Many distributions (ubuntu, debian) use dash instead of bash.
dash gives the following error:
./build.sh: 9: ./build.sh: source: not found
./build.sh: 20: cd: can't cd to /wmake
=> build.sh: use bash

.travis.yml, bld/wgml/test/test.sh, build/mif/wgmlcmd.mif
dosemu issues the useless warnings and waits for ENTER to
be pressed. Instead of messing around its configs, we can
fortunately just use the "-quiet" option to suppress all
stupid things.
=> clean up dosemu setup

bld/wipfc/cpp/document.cpp, bld/wipfc/cpp/ipffile.cpp, bld/wipfc/cpp/ipffile.hpp, bld/wipfc/cpp/main.cpp, bld/wipfc/cpp/nls.cpp, bld/wipfc/cpp/util.cpp
Since OS X doesn't define `__UNIX__` and `wipfc` uses its own configure system, we need to change the conditionals to make sense. Open to another approach to this.
=> Add OS X host support to wipfc.

bld/vi/win/getkey.c
After some refactoring/cleanup in the editor code about a year ago, the editor exits when pressing the Windows key (or any other key that is not a modified and does not correspond to an ascii code, like the Menu key).
This happens because the ConvertWierdCharacter function in getkey.c returns VI_KEY( NULL )  that slips through MapVirtualKeyToVIKey and a change about a year ago in key.c makes it exit when VI_KEY( NULL ) is found. Judging from the fact that in other places (e.g. readstr.c) there are explicit checks for NULL keys that are converted to DUMMY keys and that MapVirtualKeyToVIKey in getkey.c returns DUMMY instead of NULL when it doesn't know how to handle keys in other places, i assume the code in key.c works as expected and that ConvertWierdCharacter should return DUMMY instead …
=> Fix VIW exiting when pressing weird/system keys like the Windows key

bld/plusplus/c/type.c, bld/plusplus/gml/messages.gml
Initial work towards supporting some C++11 features.
This change generates an error if auto is used as a storage specifier in c++11 mode (compiler flag -za0x).
=> [CXX11]Removal of auto as storage class specifier (N2546)

bld/plusplus/c/anallval.c, bld/plusplus/c/type.c, bld/plusplus/h/cgfront.h, bld/plusplus/h/symtype.h, bld/plusplus/master.mif, bld/plusplus/y/plusplus.y
Now decltype  is better supported. It is still missing rvalue reference deductions but those have not been implemented yet.
=> WIP:[CXX11] Improve decltype

bld/plusplus/c/scope.c
If extensions were enabled, the compiler would treat every instance of an anonymous namespace in the same translation unit as separate namespaces.
This patch enforces that anonymous namespaces be treated as always reopening the same namespace even when extensions are on.
Closes issue #277 .
=> [CXX] Fix anonymous namespace

bld/plusplus/c/analyse.c
This is useful to diagnose some implicit conversions to bool in the future, other than being the semantically correct thing to do.
=> Replaced raw conversion to bool with implicit cast

bld/plusplus/c/analcast.c, bld/plusplus/c/analnode.c, bld/plusplus/c/analyse.c, bld/plusplus/c/cgtype.c, bld/plusplus/c/dgfront.c, bld/plusplus/c/fmttype.c, bld/plusplus/c/fnovrank.c, bld/plusplus/c/fold.c, bld/plusplus/c/icemit.c, bld/plusplus/c/membptr.c, bld/plusplus/c/ptree.c, bld/plusplus/c/scope.c, bld/plusplus/c/type.c, bld/plusplus/c/typerank.c, bld/plusplus/c/yydriver.c, bld/plusplus/gml/messages.gml, bld/plusplus/h/cgfront.h, bld/plusplus/h/ic.h, bld/plusplus/h/ptree.h, bld/plusplus/h/ptreeop.h, bld/plusplus/h/symtype.h, bld/plusplus/h/typerank.h, bld/plusplus/hash/plusplus.key, bld/plusplus/y/plusplus.y
This patch implements nullptr support in the compiler with the -za0x flag.
There are two main parts to be completed:
->implicit conversions to bool (relies on #341 to be finished)
->function overloading on std::nullptr_t
=> [CXX11] Added nullptr

bld/clib/heap/c/heapwalk.c
fix for issue https://github.com/open-watcom/open-watcom-v2/issues/356
after [this refactoring](https://github.com/open-watcom/open-watcom-v2/commit/fdfd118c51044a854e39473818857205968f5525#diff-4e91dde9823d0cc23f586c06080d4b45L133) comparison is done with Ien field instead of pointer itself
=> fix heapwalk

bld/hdr/watcom/map.mh
In accordance with the standard I added a .count method for OW's std::map implementation
=> Added .count() method to std::map

bld/rc/rc/c/scan2.c, bld/rc/rc/c/scanw.c
Increase the debug string length so it can hold the maximum signed long value.
When lexing certain numbers (such as WS_POPUP which is #defined to 0x80000000L), the resulting string gets too big and overflows the debugstring buffer.
Fix this by making the array 21 characters long, which is enough to represent the longest possible 64-bit number (-9223372036854775808), including the null character.
(This fixes the rc crash mentioned in https://github.com/open-watcom/open-watcom-v2/issues/284)
=> Fix a buffer overflow in rc

bld/clib/posix/c/_ptint.c, bld/clib/posix/c/ptcreate.c
Minor fix to initialize the TLS for the main thread in the internal pthread data structures.  Minor changes to thread initialization (mainly structure reordering).
=> Fix main thread TLS and possible segfaults on Linux with threading

bld/dig/c/dsx/trpld.c
The DIGLoader( Read ) function is already checking the size of
the read bytes and returning true or false. Comparing the return
value with imagesize will fail even if the file was loaded correctly.
=> Fix issue with trap file loader used in dos version of wd

bld/wipfc/builder.ctl
The *.cnv files used by wipfc were not being copied to rel directory by the rel target.
=> Include the *.cnv files in the wipfc rel target

cmnvars.sh
PATH variables weren't quoted properly, which caused the build scripts to fail when e.g. PATH contains a space. This typically does not occur on Linux, however, WSL tends to export Windows environment variables as well, introducing spaces.
This PR fixes this issue.
=> Fixes a bug where PATH variables were not quoted.

bld/wcl/c/owcc.c
The documentation and command-line help both say that the flag *-mstack-size* should work for the *owcc* POSIX wrapper.  However, it doesn't appear to have ever been implemented.  This small change adds support for the flag as the documentation and command-line help both say it should.
=> Actually Implemented -mstack-size Flag in owcc

bld/cc/c/cexpr.c
In SymLeaf() if we have a symbol that happens to be a typedef, SymLeaf()
fails to grab the next token. Thus, upon return to Statement(), the
compiler gets stuck in an infinite loop hoping for T_RIGHT_PAREN to
magically transform into T_SEMI_COLON.
=> cc: Fix a parsing bug related to misuse of a typedef

bld/cc/c/ctype.c
If a union contains only a bit-field, the type size is never set and
thus the type is seen as incomplete.
=> cc: Fix union type size bug

bld/cc/c/cexpr.c
ANSI C §3.2.2.1 requires that function designators be converted to
an expression of type ``pointer to function returning type`` when a
function designator is an operand of sizeof (or unary &.)
=> cc: Convert function designators when they're operands of sizeof

bld/hdr/deps.mif, bld/hdr/files.dat, bld/hdr/hfiles.mif, bld/hdr/timespec.sp, bld/hdr/watcom/signal.mh, bld/hdr/watcom/time.mh, bld/os2api/incl.mif
correct timespec structure for OS/2 to use POSIX and old BSD definition (used by IBM toolkit)
don't create sys/time.h header file for DOS-like targets
for OS/2 it is created as part of IBM toolkit in bld/os2api project
=> fix including both time.h and sys/time.h for os/2

build.sh, clean.sh
I build OW on FreeBSD/i386. I have some error. This is fixed patch.
=> use POSIX command . instead of "source" command

bld/clib/linux/c/stat.c
This is a fix for https://github.com/open-watcom/open-watcom-v2/issues/752
=> On Linux, call stat64() even from the stat() function to work around limitations with the i386 Linux kernel stat syscall on 64-bit kernels.

bld/dwarf/dr/c/drdecnam.c, bld/dwarf/dr/c/drgetref.c, bld/dwarf/dr/c/drleb128.c, bld/dwarf/dr/c/drline.c, bld/dwarf/dr/c/virtmem.c, bld/dwarf/dr/c/virtstub.c, bld/dwarf/dr/h/drleb128.h, bld/dwarf/dr/h/drline.h, bld/dwarf/dr/h/virtmem.h, bld/dwarf/dr/master.mif
correct sign extension for SLEB128 routine
enable to process 64-bit items
=> fix dwarf LEB128 reading routines

bld/wl/c/loadflat.c
Wlink's VxD generator sets some fields of the LE header based on data from the VxD's device descriptor block (DDB). However, the current code assumes that the the DDB is always at offset 0 in some segment. 
If the DDB is not at offset 0 then it just reads random data from the DDB's segment thereby writing a corrupt VxD. 
This patch fixes this. 
(having a DDB at offset 0 is not necessary for the VxD to be loaded by windows, in fact most builtin vxds have the DDB at the end of the segment).
=> fix vxd writer to account for DDB not in the start of a segment

bld/w32api/include/shlwapi.mh
We were simply missing the [PathMatchSpec alias for ANSI cases (see Remarks)](https://learn.microsoft.com/en-us/windows/win32/api/shlwapi/nf-shlwapi-pathmatchspeca).
=> Added mising ANSI macro for PathMatchSpec per Microsoft docs

bld/hdr/watcom/bios.mh, ci/ow/h/bios.h
`bios.h` did define `_diskinfo_t` as `_ibm_diskinfo`, which does not exist and I found its usage in an old codebase.
I think it should point to `_ibm_diskinfo_t`, so same as for `diskinfo_t`
=> * fix define _diskinfo_t in bios.h to _ibm_diskinfo_t

bld/graphlib/c/outtext.c
`_settextcursor` is documented to return the previous cursor shape before setting the new one - however if `_InitState` has not been called the previous cursor shape is undefined.
=> Make sure graphics state is inited before returning cursor shape

bld/plusplus/c/autodep.c
Without the fix, OpenWatcom creates broken dependency files.
(everything is in one line)
GNU Make can build the c++ autotools project once (target files are missing),
but any following make to update the targets fails with a message similar to:
*** multiple target patterns.  Stop
An example autotools project is attached:
```
./bootstrap
CC=owcc  CXX=owcc  CFLAGS="-v"  CXXFLAGS="-v"  ./configure
make
make
```
[tst_foo.tar.gz](https://github.com/open-watcom/open-watcom-v2/files/11336623/tst_foo.tar.gz)
--
Regards Detlef
=> plusplus: Fix dependency file creation (multiple target patterns)

bld/orl/test/c/test.c, bld/wl/c/cmdelf.c
I started with objread from bld/orl/test,
but that segfaults on ELF64.
A git grep for ELFOSABI made the copy&paste failure visible
wdump looked more advanced on the first sight (because it does not segfaults),
but that assumption was wrong: ELF64 does not work there either.
Elf64_Ehdr is present in bld/watcom/h, but unused in all projects other that bld/orl.
-- 
=> Add missing newline, fix a copy&paste error

bld/wcl/h/owccopts.gml
The code and the documentation use "-std=ow" to enable OpenWatcom extensions.
--
=> owcc: Fix typo in commandline help

bld/mathlib/builder.ctl, bld/mathlib/files.dat, bld/mathlib/h/ifprag.h, bld/watcom/h/libmain.h
Similar style of #1108 , this PR adds the Windows NT for MIPS platform for mathlib, it also adds a missing check for MIPS on watcom project (which fixes crt build)
=> Build mathlib for Windows NT MIPS

bld/cc/c/cpragmps.c, bld/cg/risc/mps/c/mpsdfsup.c, bld/cg/risc/mps/c/mpsenc.c
This PR fixes some CG/CC bugs for MIPS platform (32-bit/R3000) found during building of clib for Windows NT MIPS.
CG is currently still broken for ulonglong due to a "invalid opcode" error that I have yet to investigate (future PR or in this PR in case). Linking of w32api also fails probably due to wrong calling convention or similar. (which will be fixed in another PR once I figure that out)
Explanation of the changes, in case something I did was not correct or I haven't properly understood something:
Fixes the following bug: https://cdn.discordapp.com/attachments/922945502683758622/1116168969339011082/image.png
According to my research, owcc tries to search for a reduction symbol (RT_MEMCPY) symbol in the function SymAccess (csym.c:303), looking at the original Open Watcom code …
=> Fix some crashes during MIPS 32-bit code generation

bld/mstools/asaxp/c/asaxp.c, bld/mstools/cl/c/cl.c, bld/mstools/h/system.h, bld/mstools/lib/c/lib.c, bld/mstools/link/c/link.c, bld/mstools/link/c/translat.c, bld/mstools/master.mif
The following commit adds MIPS platform checks for mstools converter
=> Add mips checks for mstools

bld/plusplus/h/pcheader.h
This patch allows starting to bootstrap OW on ppc-linux
(bootstrap halts in "bld/causeway/cwc/dosi86", 
when OW try to use "wclpcc" (release version)) 
-- 
=> Portability fixes for bootstrap OW on ppc-linux

bld/ide/ide/cpp/vmsglog.cpp
I was surprised, that the action Button had the label "Öffnen" (Open), after selecting "Save As.." to save the Build Logfile.
Tested on Linux with Wine
(The WFileDialog class is implemented in bld/wclass/cpp/wfiledlg.cpp)
--
=> ide: Fix the Dialog type, when saving the build logfile

bld/wl/lnk/specs.sp
That's far from working, but a mini step.
No arch specific headers or runtime libraries for ppc-linux are available.
--
=> linuxppc: Declare a linuxppc target for wlink and owcc

bld/vi/c/edbind.c
Found while reading a recent commit.
=> vi: Fix typo in commandline help

bld/cg/doc/cgref.gml, bld/dwarf/dw/doc/dwref.gml
Welcome in the year 19123.
That's the current year on the title page of the pdf documentation of the dwarf writer library (dwdoc.pdf).
https://github.com/open-watcom/open-watcom-v2-wikidocs/blob/master/docs/dwdoc.pdf
We can`t change the binary DOS tools, but we can avoid using the buggy
":DATE. " command and hide the bug.
--
=> WGML doc: fix the year 2000 bug in the old binary DOS wgml tools

bld/cc/mps/linux386/makefile
since wccmps builds already for a x86_64-linux host, 
enable the build also for an i386-linux host feels better.
--
Regards
Detlef
=> wccmps: build the c compiler also for an i386-linux host

bld/w32api/include/directx/d3dtypes.mh
Fixing D3DTEXTUREMAGFILTER member names:
1. D3DTFG_GUASSIANCUBIC -> D3DTFG_GAUSSIANCUBIC
2. D3DTFG_ANSIOTROPIC -> D3DTFG_ANISOTROPIC
to match original names in DirectX SDKs.
Also removing check for 0x600 version. There is no such version check in DirectX 6.0 SDK, and those values definitely were supported in at least DirectX 5.0.
=> Fixing D3DTEXTUREMAGFILTER member names.

bld/w16api/include/mmsystem.mh, bld/w16api/include/win16.mh
Allow WINVER=0x300 for mmsystem.h because Windows 3.0 did add the MMSYSTEM API after release and a symbol dump of MMSYSTEM.DLL shows most of the API is there in Windows 3.0 Multimedia Edition
=> Windows header WINVER #ifdefs based on Windows 1.x and 2.x SDK headers

docs/doc/devguide/tour.gml
The default subdirectory created during the "boot" and the "bootstrap" phase
and used later was changed to "binbuild" a while ago.
Add infos about additional arch to the "as" and "cg" projects
--
=> devguide: Fix binbuild path, Update arch for as and cg

bld/w16api/include/win16.mh
Some resource flags including DS_SETFONT did not appear until Windows 3.0. Include a note stating that DS_SETFONT will cause Windows 2.x to fail to load the dialog box and why
=> Some MF_ constants like MF_OWNERDRAW did not appear until Windows 3.0

bld/rc/rc/c/semmenuw.c, bld/rc/rc/c/semsnglw.c, bld/rc/rc/h/rc.msg, bld/wres/c/resiccu.c, bld/wres/h/resiccu.h
This change allows existing ICO resources to work with Windows 2.0 provided that one of the formats contained in the ICON directory is a 64x64 monochrome image.
This also adds a warning if submenus are listed in any MENU resource when targeting Windows 2.0.
=> Windows 2x submenu check icon translation wrc 20231225 0142

bld/rc/rc/c/semsnglw.c, bld/rc/rc/h/rc.msg, bld/wres/c/resiccu.c, bld/wres/h/resiccu.h
This code also splits the image+mask code out into a common function for both CURSOR and ICON translation.
=> Resource compiler: CURSOR resource translation for Windows 2.x targets

bld/w32api/include/directx/dsound.mh
Let's use variadic macros to try to clean that up and improve maintainability
=> DirectX headers list each C-level method call twice.

docs/doc/gs/intro.gml
The old suggestion to provide telephone and fax number for service was also replaced by a suggestion to provide a valid email address.
I expect, that today no one will send a fax or make a phone call
to help fixing a bug.
Is this ok this way, or should the hint "experimental" be added in some locations?
=> c_guide: Add Linux and more Windows versions

.github/actions/artfload/action.yml, .github/actions/artfsave/action.yml, .github/workflows/artfdel.yml, .github/workflows/ci-build.yml, .github/workflows/cibldlnx.yml, .github/workflows/cibldnt.yml, .github/workflows/cibldosx.yml, .github/workflows/coverity.yml, .github/workflows/rel-lnx.yml, .github/workflows/rel-nt.yml, .github/workflows/rel-osx.yml, .github/workflows/release.yml, .github/workflows/wikidocs.yml
Node 16 is deprecated: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/
This PR contains a simple `actions/checkout` bump
~~There are breaking changes in the `@actions/download-artifacts`, which I need to read up on before updating the PR:
Basically when migrating from `actions/download-artifacts@v3` to `v4` the artifacts created by `v3` cannot be downloaded by `v4` version of the action.~~
All artifacts are build and downloaded in the same action, it's a simple ad bumping all publish/download artifact actions together
- https://github.blog/changelog/2023-12-14-github-actions-artifacts-v4-is-now-generally-available/
- https://github.com/actions/download-artifact/blob/main/README.md#breaking-changes
- …
=> deps(ci): use Node 20 based actions

bld/trmem/trmem.c
This can help to find useful areas for optimizations
When compiling OpenWatcom, I see >1 million allocations in a single project
(bld/causeway/cw32/dos386)
***Current usage: 000000000000001c bytes; Peak usage: 0000000000510ebe bytes; Allocations: 000a0091
=> trmem: Print the allocation counter in the summary

bld/exedump/c/dumpwv.c
As the title says, when a symbol name length exceeds `0x7f` the calculation for size and next position becomes negative and everything breaks.
=> fix wdump when symbol name length > 0x7f

bld/w32api/include/directx/d3dtypes.mh
The definition of the `D3DRGBA()` macro had unbalanced parentheses.
This change balances them out and also improves formatting, so it's easier to see what goes where.
=> Fix D3DRGBA() macro

bld/aui/sample/c/menus.c
This fixes a compile error on x86_64-linux
(More is needed for building on linux)
-- 
=> aui_sample: Remove wrong Prototype

bld/clib/linux/c/sysconf.c
Needed to fix sysconf(_SC_NPROCESSORS_ONLN)
Small testcase:
```
#include <stdio.h>
#include <unistd.h>
#ifndef _SC_NPROCESSORS_ONLN
#error "_SC_NPROCESSORS_ONLN not found"
#endif
int main(void)
{
long res = sysconf(_SC_NPROCESSORS_ONLN);
printf("%ld\n", res);
return 0;
}
```
The initialization of the 128 byte array increases the 
resulting program by 512 byte,
because OpenWatcom creates 128 mov instructions (even with owcc -Os`),
but that is a different issue.
--
=> clib/linux: Fix sysconf(_SC_NPROCESSORS_ONLN) result

bld/w32api/include/ddk/ntddk.mh, bld/w32api/include/nttib.sp, bld/w32api/include/winnt.mh
NT_TIB, NT_TIB32, NT_TIB64 types should be defined in h/nt/winnt.h, duplicating the definitions in h/nt/ddk/ntddk.h.
=> Define NT_TIB[32/64] types in winnt.h

bld/hdr/watcom/endian.mh
Without this fix, projects failed to compile, when "endian.h" is included early or alone.
Example: zlib-ng
https://github.com/zlib-ng/zlib-ng/blob/develop/zendian.h
(zlib-ng has portability issues, before it can be build with OpenWatcom)
#####
I checked with `git grep`, that all other header, which use `_ARCH_INCLUDE, already include "incdir.sp".
Either nearby or for "sys/socket.mh" at the start of the file.
-- 
=> endian.h: Make sure, that _ARCH_INCLUDE always works

bld/causeway/asm/api.asm, bld/causeway/asm/cw32.asm, bld/causeway/asm/ldt.asm, bld/causeway/asm/memory.asm, bld/causeway/asm/raw_vcpi.asm
do code more transparent by using NOT operator for bits reset
align comment to column 41 if possible
=> causeway: cleanup code

bld/cc/c/ppexpn.c, bld/ctest/positive/source/pp28.c
correct preprocessor in C89 mode to use 64-bit precision for expression evaluation
Now same behavior in C89 and C99 mode
correct now wrong tests for preprocessor after fixing precision
=> cc: fix for issue #1389

bld/ui/unix/c/ctkeyb.c, bld/watcom/c/clibext.c
bld/ui/unix/c/ctkeyb.c and bld/watcom/c/clibext.c is modified for initial BSD support of #1390 .
Especially, clibext.c's _cmdname() implementation is different among *BSDs.
FreeBSD:
only /proc/curproc/file supported but proc filesystem is not mounted as default.
use sysctl() to obtain information.
DragonFlyBSD:
/proc/self/exe, /proc/curproc/file, /proc/curproc/exe and FreeBSD's sysctl() interface available.
but sysctl() needs both <sys/types.h> and <sys/sysctl.h>.
due to -D_POSIX_C_SOURCE=200112L of bld/wmake/posmake, __BSD_VISIBLE and u_int is not defined and this disables sysctl(). treat as `__UNIX__`.
NetBSD:
/proc/self/exe and /proc/curproc/exe is available. treat as `__UNIX__` but  /proc/curproc/file points execute file itself (not symbolic link).
OpenBSD:
no interface for obtaining …
=> minimal fix for DragonFlyBSD/NetBSD

bld/ncurses/c/lib_baud.c, bld/wtouch/c/touch.c
continued from #1390 (my dfly branch is deleted accidentaly).
I found clibext.c has separated with `__BSD__` and `__UNIX__` code, so I did not do nothing.
support for OpenBSD is now pending. For a while we have to do work for FreeBSD, DragonFlyBSD and NetBSD.
bld/wtouch/c/touch.c and bld/ncurses/c/lib_baud.c has error, fixed.
now I am stucking bld/setupgui running sh build.sh (no option). *BSDs says:
```
============ 22:55:06 /home/uaa/open-watcom-v2/bld/setupgui/bsdx64 ============
cl setup.exe
../c/setup.c:312: error: undefined reference to 'FileInit'
../c/setup.c:366: error: undefined reference to 'FileFini'
../c/setupinf.c:1013: error: undefined reference to 'FileOpen'
../c/setupinf.c:1015: error: undefined reference to 'FileStat'
../c/setupinf.c:1018: error: undefined reference to …
```
=> add DragonFlyBSD/NetBSD support (bootstrap only) (2)

bld/watcom/c/clibext.c, bld/wipfc/icu/common/unicode/platform.h, build/dosbox.cfg
There is three commits.
1. Different from other *BSDs, OpenBSD does not have interface for obtaining filname that is currently running such as NetBSD's /proc/curproc/exe . I wrote a code that uses argv[0], realpath() and PATH environment variable to emulate that interface.
2. Unicode related code at bld/wipfc defines char16_t, but the definition is different from OpenBSD's one. This causes error. It might be avoid with -DU_HAVE_CHAR16_T at configure, but this is disabled by [configure.ac](https://github.com/open-watcom/open-watcom-v2/blob/master/bld/wipfc/configure.ac#L5). So, workaround for [wipfc/icu/common/unicode/platform.h](https://github.com/open-watcom/open-watcom-v2/blob/master/bld/wipfc/icu/common/unicode/platform.h#L752) is required. It is worth replacing with modernized ICU4C …
=> add OpenBSD support

build/dosbox.cfg, build/mif/wgmlcmd.mif
now it has no impact to other platforms except bsd clones 
dosbox.cfg hold only setup common for all platforms and specific setup is passed by command line
=> wgml-build: move bsd setup from dosbox.cfg to specific platform setup

bld/wtouch/c/touch.c
I felt curious _argv is NULL in wtouch, it is quite easy reason... it is not set.
Other modules set _argv and _argc, wtouch do same thing.
=> wtouch/c/touch.c: add _argc, _argv (clibint.h) setup

bld/f77/utils/c/errdoc.c, bld/fe_misc/c/msgencod.c, bld/fe_misc/c/optencod.c, bld/vi/c/vicomp.c
in many cases, adding argv/argc check or NULL by fopen() solve the problem.
maybe default value of FILE * variables are NULL, but I clarified it.
=> msgencod, optencod, errdoc, vicomp: fix segv without argument

bld/wstuba/builder.ctl
binb64/wstub.exe not exist, fixed.
=> bld/wstuba: add BSD support

docs/doc/owstl/algorith.gml, docs/doc/owstl/deque.gml, docs/doc/owstl/intro.gml, docs/doc/owstl/list.gml, docs/doc/owstl/owgml.gml, docs/doc/owstl/rbtree.gml, docs/doc/owstl/stack.gml, docs/doc/owstl/string.gml, docs/doc/owstl/template.gml, docs/doc/owstl/type_tra.gml, docs/doc/owstl/vector.gml, docs/doc/owstl/wowstl.gml
This change contains fixes to many typos, spelling errors, and grammar errors. It also includes general reformatting to an 80-column line width (where possible).
=> Cosmetic cleanup of OWSTL documentation

bld/lib_misc/c/aliasgen.c, bld/mstools/c/error.c
"Watcom" no longer exist as a help target
and grep found a similar error message location in the mstools
=> Update contact info for internal error message

bld/clib/posix/c/gthstent.c, bld/clib/posix/c/gtsrvent.c
If /etc/hosts or /etc/services is missing, the corresponding functions gethostent() and getservent() crash.
This patch avoids the problem by ading the missed NULL checks.
Note: the patch is trivial, but it was untested on the main OW source tree. The testing was only done on a local rip-off.
=> clib: fix NULL pointer dereferences

bld/clib/posix/c/_resolve.c
This patch is needed for a real-mode
port of that code.
Not tested in OW tree, as it doesn't
build this for real-mode.
=> resolve: reduce DNS buffer size

docs/doc/devguide/arch.gml
build/bin was renamed long ago...
=> docs: fix outdated pathname

bld/clib/posix/c/_resolve.c
It was left uninitialized.
The simplest fix, but the difficult to debug one.
=> resolver: initialize h_length

bld/hdr/null.sp, bld/hdr/watcom/_preincl.mh, bld/hdr/watcom/crtdbg.mh, bld/hdr/watcom/excpt.mh, bld/hdr/watcom/mbstring.mh, bld/hdr/watcom/stdlib.mh, bld/hdr/watcom/wchar.mh
- remove __RDOSDEV__ macro guard from non-RDOS headers
- remove DOS far functions prototype from non-DOS headers
- remove unused contents for each platform header files
=> hdr: fix bugs in header files

.gitignore, bld/trap/common/dos/dostrio.c
This pull request updates the `KeyGet` function to ensure that only the lower 8 bits of the keyboard input value are returned. This change improves compatibility with code that expects a single byte character code from keyboard input.
- Input handling improvement:
* Modified the `KeyGet` function in `dostrio.c` to mask the return value from `_BIOSKeyboardGet` with `0x00ff`, ensuring only the lower 8 bits are returned.
=> tcpserv: fixed not working 'q' for exit

.gitignore
This pull request adds .DS_Store to the project's .gitignore file to prevent it from being tracked by Git.
**What is .DS_Store?**
.DS_Store is a hidden file created automatically by macOS in a directory (folder) to store metadata. This metadata includes things like the position of icons, window view options, and other visual settings.
**How it appears on a system**
Whenever a macOS user browses a directory using the Finder application, a .DS_Store file is automatically created. These files are unnecessary for the project's functionality and are a source of clutter.
**Changes in this PR**
By adding .DS_Store to .gitignore, we ensure that this operating-system-specific file will no longer be included in the repository, making collaboration smoother for all contributors, regardless of their …
=> .DS_Store to .gitignore

bld/trap/common/dos/dosstrt.asm
Per AI (still could be a wrong assumption):
**What was broken:**
- Commit 8fea6a1519 (July 3, 2022) added `DGROUP group BEGTEXT,_TEXT,_DATA,_BSS,CONST,STACK` to dosstrt.asm
- This caused the BEGTEXT code segment to be treated as part of the data group (DGROUP)
- Function pointers in the trap header were resolved as group-relative addresses instead of simple code segment offsets
- The trap loader couldn't properly call TrapInit_, causing version check failures
**The fix:**
- Remove the `BEGTEXT,_TEXT` from DGROUP in dosstrt.asm
**Result:**
- tcpserv.exe now successfully loads std.trp without "Incorrect version of module file" errors
- The trap file signature is correctly positioned and accessible
=> trap: fixes 'Incorrect version of module file' for dos tcpserv and std.trp
