bld/clib/file/c/tempnam.c
bld/hdr/watcom/stdio.mh
bld/hdr/watcom/wchar.mh
docs/doc/lr/src/tempnam.gml

constify _tempnam() and _wtempnam()

---

bld/plusplus/c/fold.c

Make folding more aggressive, fix a bug

---

bld/hdr/watcom/_rbtree.mh
bld/hdr/watcom/set.mh
bld/hdr/watcom/vector.mh

Those functions are in standard and there are missing here
http://en.cppreference.com/w/cpp/container/vector/data
http://en.cppreference.com/w/cpp/container/set/count

Added few missing std::vector and std::set functions and const find() and count() for RedBlack tree

---

bld/clib/process/h/psp.h

A longer description of this structure can be found [here](https://en.wikipedia.org/wiki/Program_Segment_Prefix).

Added a meaningful description to psp.h

---

bld/gui/ui/c/guildstr.c
bld/wasm/c/direct.c
bld/wl/fcenable/c/fcenable.c

Fix format warnings

---

bld/trap/lcl/nt/c/accload.c
bld/trap/lcl/nt/c/accmap.c
bld/trap/lcl/nt/h/stdnt.h
bld/wsample/c/samplnx.c

use addr48_ptr type for WOW application start address

---

bld/wasm/c/macro.c
bld/wasm/c/write.c

This will be needed on osx arm.

Fix memory errors in wasm

---

bld/wl/c/cmdall.c
bld/wl/c/cmdutils.c

fix function to process expansion with regards to required token rules

fix ExpandEnvVariable function

---

bld/cc/c/asmstmt.c
bld/cc/c/cdecl1.c
bld/cc/c/cexpr.c
bld/cc/c/cmac1.c
bld/cc/c/coptions.c
bld/cc/c/cstmt.c
bld/cc/c/ctype.c
bld/cc/h/cconst.h

cleanup C compiler code

---

bld/cc/c/cdecl1.c
bld/cc/c/cdecl2.c
bld/cc/c/cenum.c
bld/cc/c/cexpr.c
bld/cc/c/cgen.c
bld/cc/c/cmac1.c
bld/cc/c/cstring.c
bld/cc/c/csym.c
bld/cc/c/ctype.c
bld/cc/c/pchdr.c

use "hash" symbol name for hash tables index variable as much as possible

cleanup code

---

bld/cc/c/cdata.c
bld/cc/c/cmac2.c
bld/cc/c/cmacadd.c
bld/cc/c/cscan.c
bld/cc/h/cvars.h

remove MacHashValue global variable and use ClacHashMacro function to calculate hash value for current macro name, not use CalcHash function for macro name anymore

add new CalcHashMacro function

---

bld/w32api/lib/kernel32.mh

Closes: https://github.com/open-watcom/open-watcom-v2/issues/889

kernel32.lib: add WakeConditionVariable, fix InitializeConditionVariable

---

bld/plusplus/c/cgbkmain.c
bld/plusplus/c/message.c
bld/plusplus/c/module.c
bld/plusplus/c/watcom.c
bld/plusplus/h/pcheader.h
bld/plusplus/h/tgtenv.h

I used the same size as ow is using in the c compiler
--

WIP: C++ compiler - changes for ppc and mips architectures

---

bld/cg/c/namelist.c
bld/cg/h/name.h
bld/cg/h/rgtbl.h
bld/cg/risc/axp/c/axprgtbl.c
bld/cg/risc/mps/c/mpsrgtbl.c
bld/cg/risc/ppc/c/ppcrgtbl.c

do code for architecture register index processing litlle transparent

cleanup cg code

---

bld/awk/master.mif
bld/causeway/cwc/master.mif
bld/cc/master.mif
bld/cg/mif/rules.mif
bld/dwarf/dw/master.mif
bld/f77/utils/master.mif
bld/f77/wfc/master.mif
bld/fe_misc/master.mif
bld/mad/master.mif
bld/ndisasm/master.mif
bld/ndisasm/test/master.mif
bld/plusplus/master.mif
bld/rc/rc/master.mif
bld/setupgui/mkdisk/master.mif
bld/testutil/master.mif
bld/trap/master.mif
bld/ui/ui.mif
bld/wasm/client.mif
bld/win386/conv/master.mif
bld/wmake/master.mif
bld/wprof/utils/makefile
bld/wsample/dump/makefile
bld/wsample/master.mif
build/mif/local.mif

new macro bld_ccl contains compile and link command and macro bld_cl contains link only command

separate linking and compile & link commands

---

bld/rc/rc/c/param.c

change -d option data type to behave similar way as old parser

fix for issue #1202

---

README.md

Fix another location of the outdated "build/bin" path

README.md: Fix the binbuild path + move it below the build entry

---

bld/watcom/h/exeelf.h

A bunch of defines and a comment to remember a struct extension
by APPLE for ARM/aarch64 (Mach-O)
--

watcom: Add more details for elf files

---

bld/docstxt/readme.sp

Adjust only a few basic infos
--

readme: Add a few Linux infos and some environment details

---

bld/watcom/h/exeelf.h

watcom/h: Fix Elf64_Phdr layout

---

bld/causeway/asm/interrup.asm

preparation to fix issue #1361

causeway: separate exception/interrupt type flag from CPU eflags

---

docs/doc/lr/src/header.gml

Added/rewritten as per https://github.com/open-watcom/open-watcom-v2/issues/1373#issuecomment-2598659558

chore(doc): update header.gml info about dos.h structs

---

bld/causeway/asm/cw32.asm
bld/causeway/asm/raw_vcpi.asm

add new structure for VCPI switch mode related data to do code more transparent

causeway: cleanup code

---

bld/setupgui/c/setup.c
bld/setupgui/c/strvbuf.c
bld/setupgui/c/utils.c
bld/setupgui/h/setup.h
bld/setupgui/h/utils.h

prepare to introduce file systems array instead of DOS-ish drive character and number

setupgui: cleanup code

---

bld/gui/doc/guide.doc
bld/gui/doc/plat.doc

Removed also some Hints in the guide,
which are no longer needed with the current build system.

gui/doc:  Small cleanup for the gui library documentation

---

bld/clib/posix/c/_resolve.c

resolver: fix leak of query_socket

---

bld/graphlib/h/arcinfo.h
bld/graphlib/h/font8x8.h
bld/graphlib/h/gbios.h
bld/graphlib/h/gdefn.h
bld/graphlib/h/grdev.h
bld/graphlib/pgchart/h/pgvars.h

Use pragma __pack for each structure which require it, don't use it globaly
remove unused prototype
restructure header files

graphlib: cleanup code
